In [2]:
import torch
import numpy as np
import pandas as pd
import d2l

In [3]:
x = torch.arange(12.)
x.reshape(3,4)
x.requires_grad = True

In [4]:
print(x.grad)

None


In [5]:
y = torch.mm(x.reshape(3,4),x.reshape(4,3))
y.sum().backward()
x.grad

tensor([15., 24., 33., 45., 18., 27., 39., 48., 21., 33., 42., 51.])

## 求二阶导

In [33]:
x = torch.tensor([3.,4.])
x.requires_grad = True
z = x**3
# backward方式

z.sum().backward(create_graph=True)
print(x.grad)
x.grad.data.zero_()
x.grad.sum().backward()
print(x.grad)

tensor([27., 48.], grad_fn=<CopyBackwards>)
tensor([18., 24.], grad_fn=<CopyBackwards>)


In [34]:
x = torch.tensor([3.,4.])
x.requires_grad = True
z = x**3

# autograd方式
grad_x = torch.autograd.grad(z.sum(), x, create_graph = True )
grad_x2 = torch.autograd.grad(outputs = grad_x[0].sum(), inputs = x) #grad_x的第一项才是梯度张量
print(grad_x)
print(grad_x2)

(tensor([27., 48.], grad_fn=<MulBackward0>),)
(tensor([18., 24.]),)
